version: '3.8'

services:
  comerciotech-nosql_v2:
    image: mongo:7.0
    container_name: comerciotech_nosql-v2
    restart: always
    environment:
      # 🔑 CREDENCIALES EN BRUTO PARA EL ADMINISTRADOR RAÍZ DE MONGO
      - MONGO_INITDB_ROOT_USERNAME=admin_root
      - MONGO_INITDB_ROOT_PASSWORD=SecretMongo2026*
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./scripts-mongo:/docker-entrypoint-initdb.d:ro
    command: [ "--auth" ]
    networks:
      - comerciotech_net

  comerciotech-sql:
    image: mysql:8.0
    container_name: comerciotech_sql
    restart: always
    environment:
      # 🔑 CREDENCIAL EN BRUTO PARA EL ADMINISTRADOR RAÍZ DE MYSQL
      - MYSQL_ROOT_PASSWORD=AdminComercio2026*
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts-sql:/docker-entrypoint-initdb.d:ro
    networks:
      - comerciotech_net

  comerciotech_app:
    # 💡 CORREGIDO: Compila usando el Dockerfile de la carpeta donde estás parado
    build: .
    container_name: comerciotech_app
    depends_on:
      - comerciotech-nosql-v2
      - comerciotech-sql
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    stdin_open: true
    tty: true
    networks:
      - comerciotech_net

networks:
  comerciotech_net:
    driver: bridge

volumes:
  mongo_data:
  mysql_data:
