version: '3.8'

services:
  comerciotech-nosql-v2:
    image: mongo:7.0
    container_name: comerciotech_nosql_v2
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_APP_USER=${MONGO_APP_USER}
      - MONGO_APP_PASSWORD=${MONGO_APP_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./scripts-mongo:/docker-entrypoint-initdb.d:ro
    command: [ "--auth" ]
    networks:
      - comerciotech_net
    deploy:
      resources:
        limits:
          memory: 2.7G
        reservations:
          memory: 1.5G

  comerciotech-sql:
    image: mysql:8.0
    container_name: comerciotech_sql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts-sql:/docker-entrypoint-initdb.d:ro
    networks:
      - comerciotech_net
    deploy:
      resources:
        limits:
          memory: 2.0G
        reservations:
          memory: 1.0G

  comerciotech_app:
    build: .
    container_name: comerciotech_app
    depends_on:
      - comerciotech-nosql-v2
      - comerciotech-sql
    restart: always
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
      - APP_SECRET_KEY=${APP_SECRET_KEY}
    ports:
      - "127.0.0.1:8080:8080"
    stdin_open: true
    tty: true
    networks:
      - comerciotech_net

networks:
  comerciotech_net:
    driver: bridge

volumes:
  mongo_data:
  mysql_data: